# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates the monthly water balance using ABCD cold region model . 
#'
#'
#' @param date  is a monthly time series Date
#'  @export
#'  @import data.table
#' @examples
#' para_a=.5
#' para_b=200
#' para_c=1
#' para_d=.5
#' SWS_ini=20
#' S_ini=10
#' G_ini=100
#' alpha=0.03
#' beta=.143
#' Gmax=5
#'  m<-c()
#' m$Date<-seq(as.Date("2014/1/1"), by="month" ,length.out =12)
#' m$p= c(100:111)
#' m$PE=c(50:61)
#' m$temp=c(-5:6)
#' dt<-as.data.table(m)
#' dt[, ABCD_CR:= abcd_cr(para_a, para_b, para_c, para_d, SWS_ini, S_ini, G_ini, p, PE, temp, alpha, beta, Gmax)]
#' dt
abcd_cr <- function(para_a, para_b, para_c, para_d, SWS_ini, S_ini, G_ini, p, PE, temp, alpha, beta, Gmax) {
    .Call(`_Hydro_abcd_cr`, para_a, para_b, para_c, para_d, SWS_ini, S_ini, G_ini, p, PE, temp, alpha, beta, Gmax)
}

#' Calculates the monthly water balance using ABCD cold region model . 
#'
#'
#' @param date  is a monthly time series Date
#'  @export
#'  @import data.table
#' @examples
#' para_a=.5
#' para_b=200
#' para_c=1
#' para_d=.5
#' S_ini=10
#' G_ini=100
#'  m<-c()
#' m$Date<-seq(as.Date("2014/1/1"), by="month" ,length.out =12)
#' m$p= c(100:111)
#' m$PE=c(50:61)
#' m$temp=c(-5:6)
#' dt<-as.data.table(m)
#' dt[, ABCD_mm:= abcd_month_model_cpp(para_a, para_b, para_c, para_d, S_ini, G_ini, p, PE)]
#' dt
NULL

abcd_month_model_cpp <- function(para_a, para_b, para_c, para_d, S_ini, G_ini, p, PE) {
    .Call(`_Hydro_abcd_month_model_cpp`, para_a, para_b, para_c, para_d, S_ini, G_ini, p, PE)
}

#' Calculates the potential evaporation using Oudin method . This method uses the input vector of  monthly date time series, temperature and longitude values.
#'
#'
#' @param date  is a monthly time series Date
#'  @param tavg  is a monthly mean time series of temperature
#'  @param lat  is a vector of longitude
#'  @return is monthly potential evaporation in mm/day
#'  @export
#'  @import data.table
#' @examples
#'  m<-c()
#' m$Date<-seq(as.Date("2014/1/1"), by="month" ,length.out =12)
#' m$Temp<-c(3.1, 3.5, 5.0, 6.7, 9.3, 12.1, 14.3, 14.1, 11.8, 8.9, 5.5, 3.8)
#' m$lat<-rep(57.1526, 12)
#'  dt<-as.data.table(m)
#' dt[, PET_Hamon:= pet_oudin_cp(Date, Temp, lat)]
#' dt
pet_oudin_cp <- function(date, tavg, lat) {
    .Call(`_Hydro_pet_oudin_cp`, date, tavg, lat)
}

#' Calculates the monthly water balance using ABCD cold region model . 
#'
#'
#' @param date  is a monthly time series Date
#'  @export
#'  @import data.table
#' @examples
#' para_a=.5
#' para_b=200
#' para_c=1
#' para_d=.5
#' S_ini=10
#' G_ini=100
#'  m<-c()
#' m$Date<-seq(as.Date("2014/1/1"), by="month" ,length.out =12)
#' m$p= c(100:111)
#' m$PE=c(50:61)
#' m$temp=c(-5:6)
#' dt<-as.data.table(m)
#' dt[, ABCD_CR:= abcdseList(para_a, para_b, para_c, para_d, S_ini, G_ini, p, PE)]
#' dt
NULL

abcdseList <- function(para_a, para_b, para_c, para_d, p, PE, S_ini, G_ini) {
    .Call(`_Hydro_abcdseList`, para_a, para_b, para_c, para_d, p, PE, S_ini, G_ini)
}

#' estimate the month using monthly time series of date . 
#'
#'
#' @param date  is a monthly time series Date
#'  @export
#'  @import data.table
#' @examples
#'  m<-c()
#' m$Date<-seq(as.Date("2014/1/1"), by="month" ,length.out =12)
#' dt<-as.data.table(m)
#' dt[, month:= month_cp(Date)]
#' dt
NULL

#' estimate the day using monthly time series of date . 
#'
#'
#' @param date  is a monthly time series Date
#'  @export
#'  @import data.table
#' @examples
#'  m<-c()
#' m$Date<-seq(as.Date("2014/1/1"), by="month" ,length.out =12)
#' dt<-as.data.table(m)
#' dt[, day:= day_cp(Date)]
#' dt
day_cp <- function(date) {
    .Call(`_Hydro_day_cp`, date)
}

month_cp <- function(date) {
    .Call(`_Hydro_month_cp`, date)
}

year_cp <- function(date) {
    .Call(`_Hydro_year_cp`, date)
}

#' Calculates the julian day using monthly time series of date . 
#'
#'
#' @param date  is a monthly time series Date
#'  @export
#'  @import data.table
#' @examples
#'  m<-c()
#' m$Date<-seq(as.Date("2014/1/1"), by="month" ,length.out =12)
#' dt<-as.data.table(m)
#' dt[, JD:= julianday_cp(Date)]
#' dt
julianday_cp <- function(date) {
    .Call(`_Hydro_julianday_cp`, date)
}

AHI <- function(date, temperature) {
    .Call(`_Hydro_AHI`, date, temperature)
}

#' Calculates the potential evaporation using Thornwaite method . This method uses the input vector of  monthly date time series, temperature and longitude values.
#'
#'
#' @param date  is a monthly time series Date
#'  @param tavg  is a monthly mean time series of temperature
#'  @param lat  is a vector of longitude
#'  @return is monthly potential evaporation in mm/month
#'  @export
#'  @import data.table
#' @examples
#'  m<-c()
#' m$Date<-seq(as.Date("2014/1/1"), by="month" ,length.out =12)
#' m$Temp<-c(3.1, 3.5, 5.0, 6.7, 9.3, 12.1, 14.3, 14.1, 11.8, 8.9, 5.5, 3.8)
#' m$lat<-rep(57.1526, 12)
#'  dt<-as.data.table(m)
#' dt[, PET_Hamon:= pet_thorn_cpp(Date, Temp, lat)]
#' dt
pet_thorn_cpp <- function(date, tavg, lat) {
    .Call(`_Hydro_pet_thorn_cpp`, date, tavg, lat)
}

#' Calculates the potential evaporation using Hamon method . This method uses the input vector of  monthly date time series, temperature and longitude values.
#'
#'
#' @param date  is a monthly time series Date
#'  @param tavg  is a monthly mean time series of temperature
#'  @param lat  is a vector of longitude
#'  @return is monthly potential evaporation in mm/day
#'  @export
#'  @imports data.table
#' @examples
#'  m<-c()
#' m$Date<-seq(as.Date("2014/1/1"), by="month" ,length.out =12)
#' m$Temp<-c(3.1, 3.5, 5.0, 6.7, 9.3, 12.1, 14.3, 14.1, 11.8, 8.9, 5.5, 3.8)
#' m$lat<-rep(57.1526, 12)
#'  dt<-as.data.table(m)
#' dt[, PET_Hamon:= pet_hamon(Date, Temp, lat)]
#' dt
pet_hamon <- function(date, tavg, lat) {
    .Call(`_Hydro_pet_hamon`, date, tavg, lat)
}

rcpp_hello_world <- function() {
    .Call(`_Hydro_rcpp_hello_world`)
}

